### ISSUE TITLE
Unchecking "Show Non-Video Participants" while in voice chat causes crash

### ISSUE THREAD

**Issue by Nanorithm** [asportnoy/role-color-everywhere#2] opened 2023-06-21 19:15 UTC
Unchecking the top option here causes crashing.

![image](https://github.com/asportnoy/role-color-everywhere/assets/13856563/c27664db-fbd7-4c08-9bc9-5f5b0a041c48)

It only happens when this plugin is enabled, disabling it stops it from crashing.

From console: 

![image](https://github.com/asportnoy/role-color-everywhere/assets/13856563/c127f18c-f52e-4b0e-a6f0-db111a602c62)

Above is as soon as I uncheck the box. Using version 1.3.1

**Comment by asportnoy** [comment] 2023-06-22 15:13
Should be fixed by 816c45b890bbd0bf757af98327417b625f391edb (pending review)

**Closed as completed by asportnoy** 2023-06-22 15:13 UTC

**Comment by asportnoy** [comment] 2023-06-22 15:23
v1.3.2 released with this fix, let me know if the issue is fixed or not.

**Comment by Nanorithm** [comment] 2023-06-22 16:40
This fixed my issue thank you for the quick response!
